
#
# Problem 45:
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:
#       Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
#       Pentagonal 	  	Pn=n(3n-1)/2 	  	1, 5, 12, 22, 35, ...
#       Hexagonal 	  	Hn=n(2n-1) 	  		1, 6, 15, 28, 45, ...
# 
# It can be verified that T285 = P165 = H143 = 40755.
# 
# Find the next triangle number that is also pentagonal and hexagonal.
#

# The number of Tn/Pn/Hn numbers to find.
$to_find = 2;

# This will keep track of the number found.
$found = 0;

# The initial starting values for each n.
$tn = 1, $pn = 1, $hn = 1;

# The initial starting values for each number.
$t = 1, $p = 1, $h = 1;

# Continually iterate until we find the right number.
while ($found < $to_find) {
	# Increment Hn to the next value.
	$hn++; 

	# Find the h value.
	$h = $hn * (2 * $hn - 1);

	# Find the next p value.
	while ($p < $h) {
		# Increment Pn to the next value.
		$pn++;

		# Find the p value.
		$p = $pn * (3 * $pn - 1) / 2;
	}

	# Skip to the next iteration if P != H.
	next if ($p != $h);

	# Find the next t value.
	while ($t < $h) {
		# Increment Pn to the next value.
		$tn++;

		# Find the t value.
		$t = $tn * ($tn + 1) / 2;
	}

	# Skip to the next iteration if T != H.
	next if ($t != $h);

	# Print that we found one.
	print "Found T$tn = $P$pn = H$hn = $h\n";

	# Increment the counter.
	$found++;
}

